### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by fluet** [dghubble/sling#11]
Hello,

May I know if you've any example code for file upload?

Thanks.

**Comment by dghubble** [comment]
I don't include one. Maybe make a case for that helper via a PR?

**Comment by fluet** [comment]
Thanks for the reply. I'll see if I can help on that as I'm still new to Go.

**Comment by alaska** [comment]
How would you want this to fit into the lib? Something that takes an os.File or a string? Both? Where should it go in the architecture? I can take a crack at it.

**Comment by dghubble** [comment]
I'm not sure that it belongs in this library unless we find common boilerplate being repeated over and over across APIs which support uploads of various sorts. So far I haven't looked into enough to have a definite yes/no or had the need. If it were me, I'd aim for io.Reader when drafting it out.

**Comment by AaronO** [comment]
@alaska @dghubble It seems like https://github.com/dghubble/sling/pull/23 would facilitate this.

His `MultipartBody` would do the bulk of the heavy lifting required to upload files: https://github.com/dghubble/sling/pull/23/files#diff-4b36830cc40bc7940158a9d0bf745624R45

This could be complemented by a `MultipartStreamBody(files map[string]io.Reader, extraParams map[string]string) BodyProvider` to allow uploading `io.Reader` or `os.File` streams.

These could then be wrapped in convenient `Upload` and `UploadStreams` methods.

@dghubble I agree with you that it is doable outside this lib, but it can be quite verbose and tricky for beginners (e.g: https://github.com/GitbookIO/go-gitbook-api/blob/master/api/builds.go#L112-L155), so if we can get it right in `sling` it would allow advanced and beginner devs to use `sling` to easily build nice API clients without tricky custom code.

**Comment by AaronO** [comment]
@dghubble I understand and agree with you that `sling` should be kept simple and opinionated.

Uploading is not one of those common features that everyone uses (REST APIs, json serialization), but it's painful and important enough for those who do use it that it might be worth integrating into `sling` (if we can get it right).

<a href="http://www.slideshare.net/MaximeBraud/road-to-a-great-product-methods-tools-and-hacks/23-Map_your_features_into_4"><img width="638" alt="screen shot 2016-09-19 at 6 38 14 pm" src="https://cloud.githubusercontent.com/assets/949223/18640418/5eb4449a-7e98-11e6-99de-6addfc4c2b64.png"></a>

**Comment by jawher** [comment]
@dghubble Now that body providers are merged, how do you like the file upload to be handled ? Do I make a PR to add it to sling (in a sub-package maybe ?) or do you rather want it to keep it as a separate project ?

**Comment by dghubble** [comment]
Sure, if its no trouble, it would be good to see some provider implementations posted for that. They can simmer for a bit, they're easy enough to copy paste and try out within their apis before one is adopted as the default `BodyMultipart` setter.

Sub-packaging is only needed if there are extra imports that wouldn't otherwise be needed. I think its fine in a `multipart.go` for stdlib deps.

**Comment by jawher** [comment]
It's never too late ! After a gruelling 5 months of hard work and extensive testing, I was able to produce the following (~150 lines) multipart body provider for Sling :trollface: 

https://github.com/jawher/sling.upload

**Comment by dghubble** [comment]
Now that `bodyProviders` are an interface, folks can implement various sorts of uploads directly. https://github.com/jawher/sling.upload is an example. This can be closed.
