### ISSUE TITLE
how to receive plain text?

### ISSUE THREAD

**Issue by harryge00** [dghubble/sling#13]
The "client.Do()" is based on "decodeResponseJSON", what if I just want to receive the whole http.response body as string without json struct?

**Comment by dghubble** [comment]
Create an `http.Request` and Do it with the standard `net/http` `Do` (i.e. https://golang.org/pkg/net/http/#Client.Do)

```
import "net/http"

req, err := sling.New().Get("https://example.com").QueryStruct(params).Request()
client := http.DefaultClient
resp, err := client.Do(req)
```
