### ISSUE TITLE
client middleware

### ISSUE THREAD

**Issue by ansel1** [dghubble/sling#15]
Would it be useful to support using client middleware functions, of the form:

```go
type ClientMiddlewareFunc func(*http.Request) (*http.Response, error)
```

Such middleware could modify or log requests and responses.  Logging middleware would be an obvious use case.

**Comment by dghubble** [comment]
Users have access to the `http.Request` and `http.Response` (would be improved by #10) already, to whatever they like. What is the underlying use case for a middleware type to be a part of Sling?

**Comment by ansel1** [comment]
Debug logging without having to change any of the code using sling.  Say I wanted to add debug logging of all requests and responses.  If I have a bunch of code already using sling, I'd need to modify that code: I'd need to replace calls to ReceiveXXX() with calls to Request() and Do().  And as noted in #10, I currently don't have access to the Response's body.

Even if #10 were implemented, allowing me to intercept both the Request and the full Response (with body) for logging/debugging purposes, I then would not be able to use sling to decode the response bodies: #10 suggests I would need to choose between Do() (in which case I have to do the decoding) or DoDecode() (in which case, sling does the decoding for me, but I have don't get access to the raw body).

If I have a bunch of code, already using sling, using the Recieve() methods, and I want to drop in calls to httputil.DumpRequest() and httputil.DumpResponse(), and turn that on and off based on a runtime flag, without modifying existing code, I don't think I can do that without the notion of a client middleware stack.

The basic notion of middleware has proven to be a robust design on the server side, so why not also on the client side.

**Comment by ansel1** [comment]
Also, I think middleware might provide an alternative to #10 that would not require breaking sling's API.  I could install middleware which intercepts the response and handles whacky responses.  For example, I have an API which returns json on success, but text on error.  If I'm using sling, I unfortunately can only use sling to compose the http.Request.  I can't leverage sling's nice Recieve() api.  

With middleware, I could intercept the error responses and capture the error response body text, while still taking advantage of sling for the success path.

**Comment by PuerkitoBio** [comment]
IMO only changing the `Client(*http.Client) *Sling` method to `Client(Doer) *Sling` signature provides all of the benefit without having to support middleware directly in sling (that is, callers compose their Doer as they like before passing it to the sling API). If I checked correctly, sling already uses only the `Do` method of the client so it's a trivial change. I blogged about it into more details here: https://0value.com/Let-the-Doer-Do-it.

Of course that's still a breaking change for the API even though most cases would still compile without error, so it's up to you to decide whether to change the signature or add a different method, but I think there are nice benefits in supporting this (logging as already mentioned, but also mocking tests of API calls based on sling).

**Comment by ansel1** [comment]
Yeah, that's a much better way to do it.  I withdraw my suggestion.

**Comment by dghubble** [comment]
Nice. Accepting an `http.Client` but mediating through a

```
type Doer interface {
  Do(req *http.Request) (*http.Response, error)
}
```

distills our usage of the `http.Client` (only using `Do`) and is compatible with any standard `http.Client`. Exposing the `Doer` allows folks to optionally write their own request/response handling if they don't want to use a Client/Transport and avoids introducing a middleware `type` users must import and be subjected to.

:+1:

**Comment by dghubble** [comment]
https://github.com/dghubble/sling/pull/21
