### ISSUE TITLE
Feature: Configurable decoder

### ISSUE THREAD

**Issue by ansel1** [dghubble/sling#17]
Add func (*Sling) Decoder(d DecoderFunc) *Sling

type DecoderFunc func (resp *http.Response, v interface{}) error

Alternately, use a Decoder/DecoderFunc pattern, like http.Handler/HandlerFunc.  Whatever your preferred style.

Would allow taking over the decoding process, to handle cases like mime types other than json, or error responses with different mimetypes.  Another possible solution to #10 (i.e. handling the body before its closed) without breaking the API

**Comment by dghubble** [comment]
Looks like this is handled by #21, thanks.
