### ISSUE TITLE
allow JSON response decoding for response with Content-Type != "application/json"

### ISSUE THREAD

**Issue by genez** [dghubble/sling#24]
It would be helpful with legacy API's that sadly work with "text/plain" or other content types such as "application/json+oembed".

I think you could just remove the check, as you already handle the JSON decoder failure.
If you don't want to remove the header check, maybe a new function with a easy-to-understand name like "ReceiveSuccessJSON" could do the trick

**Comment by dkushner** [comment]
I would like to second this and add my more contemporary use case of needing to interact with a strictly compliant JSON-API endpoint that returns only content type of `application/vnd.api+json`.
