### ISSUE TITLE
Any good docs or examples on testing sling services with a mock server?

### ISSUE THREAD

**Issue by deinspanjer** [dghubble/sling#28]
I was previously using jarcoal/httpmock with our raw net/http REST client code, but I wasn't sure how properly to mock out the server when dealing with a sling service.

Are there any good examples for this?

**Comment by ericchiang** [comment]
@deinspanjer https://golang.org/pkg/net/http/httptest/?

**Comment by dghubble** [comment]
Check the go-twitter API package: [testServer](https://github.com/dghubble/go-twitter/blob/master/twitter/twitter_test.go#L18) and [usage](https://github.com/dghubble/go-twitter/blob/master/twitter/statuses_test.go#L12).

**Comment by deinspanjer** [comment]
Thank you very much for the tips
