### ISSUE TITLE
Bump version ? (v1.0.0 was released over a year ago)

### ISSUE THREAD

**Issue by AaronO** [dghubble/sling#29]
Hi @dghubble, `v1.0.0` was released over a year ago and a few things have been added to `sling` since (e.g: `.SetBasicAuth()`, BodyProviders, etc ...), do you think you could bump `sling` and ship a new release ?

This would benefit users of `glide` and other vendoring solutions so that they could point to a more meaningful version than a `SHA`.

**Comment by dghubble** [comment]
Yeah, its about time for a v1.1.0.

**Comment by AaronO** [comment]
@dghubble Thanks, I appreciate the release !
