### ISSUE TITLE
Use a map of strings for parameters

### ISSUE THREAD

**Issue by maxzerbini** [dghubble/sling#30]
Hi Dalton,

 great work! I love this library!

I've just a little suggestion, what do you think about adding a new method 
_QueryString(params map[string]string) *Sling_
alternative to _QueryStruct()_ that add query string parameters.
Using a map of strings can be easier and does not require reflection.
Sling should support both methods ensuring backward compatibility.

If you'll agree, I can make a pull request with this little change.

Regards,
Massimo

**Comment by kminehart** [comment]
It would have to be

```
QueryString(params map[string][]string) *Sling
```

Which would just be https://golang.org/pkg/net/url/#Values

**Comment by maxzerbini** [comment]
Yes, it is. 
It's just a wrapper of the method Values, but it can be used fluently as the other Sling APIs.

**Comment by dghubble** [comment]
Sling gives direct access to the `http.Request` and I agree, the standard library already has `url.Values` for this. I'd like to avoid adding wrappers for things that are already nicely done by using the standard library.

Thanks for the suggestion though.
