### ISSUE TITLE
Can't seem to get QueryStruct() to work

### ISSUE THREAD

**Issue by kellabyte** [dghubble/sling#32]
When I sniff the traffic over Wireshark I don't see the query parameters being passed in the URL. What am I doing wrong?

```
// Params represents the query parameters to Zipkin.
type Params struct {
	serviceName string `url:"endts,omitempty"`
	spanName string `url:"endts,omitempty"`
	endTs string `url:"endts,omitempty"`
	lookback string `url:"endts,omitempty"`
	limit int `url:"endts,omitempty"`
	annotationQuery string `url:"annotationquery,omitempty"`
}

params := Params{
	serviceName: serviceName,
	spanName: allSpans,
	endTs: startTs,
	lookback: endTs,
	limit: limit,
	annotationQuery: "event.type=foo",
}

_, err := sling.New().Get("http://127.0.0.1:31152/api/v1/traces").
        QueryStruct(params).
        Receive(&traces, nil)

```

**Comment by dghubble** [comment]
https://godoc.org/github.com/google/go-querystring/query defines the struct tags url query parameters can take. "Each exported struct field is encoded as a URL parameter unless..." - like JSON struct tags, the fields need to be exported (capitalized). Also, its seems odd the name of each field is set to "endts", I'm not sure why that would be desired.

Valid example https://github.com/dghubble/sling#querystruct

**Comment by dghubble** [comment]
@kellabyte I think this solves your issue. Please re-open if not!
