### ISSUE TITLE
Some APIs can't handle trailing slashes

### ISSUE THREAD

**Issue by naveens** [dghubble/sling#35]
When Base URL is set with a trailing slash (for later Path extension) and a request is made, some APIs give an error response. Unfortunately, these APIs can't handle trailing slashes.

It might be useful to have a sling method (TrimSlash?) to remove the trailing slash(es).

**Comment by dzirg44** [comment]
I use sling in several projects where there are links with the slash and without it. But I have never faced such problems. Perhaps the link example would be a good starting point.

**Comment by dghubble** [comment]
You can construct a sling without a trailing slash. And for your path extension use cases, have a different sling. They're just little request builders at the end of the day, they're cheap.
