### ISSUE TITLE
Is there a reason to return same object vs copy?

### ISSUE THREAD

**Issue by zbintliff** [dghubble/sling#36]
Is there a reason why you modify the sling object directly?  I can't really think of an example in where I want my query parameters to stick around. And if that is the case I would save that.  Other librarie that allow chaining (gorm for example) return a NEW object after every call.

The fact that you mutate the same sling object means that ther user has to be aware of it and constantly call new. WHen in most cases, after something is stored in a field we want to keep going back to that state. For example, we set a base url set to a field in the client and then constantly call it without calling .New().

**Comment by zbintliff** [comment]
BTW since you have New() written and it already clones, it would be a small change to implement

**Comment by zbintliff** [comment]
Closing this out becuse its so explicit in the Documentation I feel this was an issue many people have.  Still disagree with the chaining mutation but :man_shrugging:

**Comment by dghubble** [comment]
Having the API perform a full copy on each set (mutation) takes that decision away from the caller. Right now, the caller may explicitly choose when to perform a full copy. You may also wrap small wrappers (or a fork on top) that call `New` on each mutation if you so choose and don't care about cost.
