### ISSUE TITLE
Can we have a separate method to return raw response, err from httpClient?

### ISSUE THREAD

**Issue by hiteshsethi** [dghubble/sling#37]
The current method:

`func (s *Sling) Do(req *http.Request, successV, failureV interface{})`

expects you send `successV`, `failureV` and even if we pass it `nil, nil` we internally close the response body. 

Can we have a separate method in sling just to return raw response, err or in `func (s *Sling) Do` close the body only when either of  `successV` or `failureV` is not `nil` ?

**Comment by dghubble** [comment]
The first usage example shows how to get the raw `http.Request` and use `http` [client.Do](https://golang.org/pkg/net/http/#Client.Do) to send it and get the response. There is no need for Sling to have a method for this.

**Comment by hiteshsethi** [comment]
@dghubble thanks for response.
I agree, but since sling is already taking httpClient in its object with `func (s *Sling) Client` method, it would be better if we can use `slingClient.HttpClient.Do` or `slingClient.RawDo`.

For example, If I'm using some helper method to make client and use everywhere:

`
func GetSlingHttpClient() *sling.Sling {
	netClient := &http.Client{
		Timeout:   time.Second * BrokerTimeoutInSeconds,
		Transport: getNetTransport(),
	}
	slingClient := sling.New().Client(netClient)
	return slingClient
}`

Then I also have to expose the httpClient which I'm using everywhere also. 

It would be really nice if we can have some getter method to access to `httpClient` or provide some method to let user read the raw response body.
