### ISSUE TITLE
Using Post after Path does not append but replace path

### ISSUE THREAD

**Issue by sluongng** [dghubble/sling#43]
As title said, I noticed that using Post after Path simply replaced the whole Path with was set previously.
if Path().Path() stack, shouldnt same can be applied to Path().Post()?

Verb function should only reset the Method right?

**Comment by dghubble** [comment]
https://github.com/dghubble/sling/blob/master/README.md#path

> Extension means the path will be resolved relative to the existing URL.

What's the argument to the first `Path(?)` in the chain? Extending the path resolves relative to the existing URL (i.e. defined so far) uses Go's relative path resolution. `.Path("foo").Path("bar")` vs `.Path("foo/").Path("bar")`
